CREATE TABLE LOGS (
	ID BIGINT NOT NULL,
	MESSAGE VARCHAR(500),
	CONNECT_ID INTEGER,
	COST NUMERIC(15,2),
	CREATE_AT DATE,
	"REF" VARCHAR(50),
	DEFAULT_COST NUMERIC(15,2) DEFAULT 0 NOT NULL,
	"BOOLEAN" CHAR(1) DEFAULT 'N',
	DOCUMENT BLOB SUB_TYPE -15,
	NOTES BLOB SUB_TYPE TEXT,
	SATS DOUBLE PRECISION DEFAULT 24.00,
	NEGATIVE_NUM  SMALLINT DEFAULT -20,
	CONSTRAINT PK_AGENTLOGG PRIMARY KEY (ID)
);
