CREATE TABLE LOGS (
	ID BIGINT NOT NULL,
	MESSAGE VARCHAR(500),
	CONNECT_ID INTEGER,
	COST NUMERIC(15,2),
	CREATE_AT DATE,
	"REF" VARCHAR(50),
	DEFAULT_COST NUMERIC(15,2) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_AGENTLOGG PRIMARY KEY (ID)
);
