
CREATE TABLE CONNECTIONS (
	CONNECT_ID BIGINT NOT NULL,
	MESSAGE VARCHAR(500).
	IS_INSTERNAL CHAR(1) DEFAULT 'J',
);

CREATE TABLE LOGS (
	ID BIGINT NOT NULL,
	MESSAGE VARCHAR(500),
	CONNECT_ID INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_AGENTLOGG PRIMARY KEY (ID),
	CONSTRAINT FK_CONNECTION FOREIGN KEY (CONNECT_ID) REFERENCES CONNECTIONS(CONNECT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
);
