
CREATE TABLE LOGS (
	ID BIGINT NOT NULL,
	MESSAGE VARCHAR(500),
	CONNECT_ID INTEGER,
	CONNECT_COUNTER INTEGER,
	CONSTRAINT PK_AGENTLOGG PRIMARY KEY (ID)
);

CREATE TRIGGER LOGG_OF_CONNECTION_ID FOR LOGS BEFORE INSERT
AS
begin
  new.logg_connect_id = substring(TEST from i for 1);
end;
