CREATE TABLE LOGS (
	ID BIGINT NOT NULL,
	MESSAGE VARCHAR(500),
	CONNECT_ID INTEGER,
	CONSTRAINT PK_LOGS PRIMARY KEY (ID)
);

CREATE TABLE FROGS (
	ID BIGINT NOT NULL,
	FROG_NAME VARCHAR(500),
	CONSTRAINT PK_FROGS PRIMARY KEY (ID)
);
